"use client";

import { useCallback } from "react";
import { useI18n } from "@/components/i18n/I18nProvider";
import { byLocale } from "@/lib/i18n/select";

const EN_TEXT = {
  none: "None",
  failedFhirExplorerProjectImport: "Failed to import FHIR Explorer project file.",
  fhirExplorerProjectImported:
    "FHIR Explorer project imported ({imported} packages, {skipped} skipped).",
  packageAlreadyImported: "Package {packageKey} is already imported.",
  targetPackageImported: "Target package {packageKey} imported.",
  dependencyImported: "Dependency {packageKey} imported.",
  packageImportedButNotMissing:
    "Package {packageKey} imported, but it was not listed as missing.",
  targetPackageAlreadyImported: "Target package {packageKey} is already imported.",
  importingPackage: "Importing package",
  packageAlreadyImportedShort: "Package {packageKey} already imported.",
  importedPackageShort: "Imported {packageKey}.",
  errorPrefix: "Error: {error}",
  title: "Package Import",
  importer: "FHIR Importer",
  cancelImport: "Cancel Import",
  projectsOverview: "Projects Overview",
  home: "Home",
  intro:
    "Import FHIR packages and every transitive dependency entirely in the browser. The wizard updates after each upload.",
  imported: "Imported: {count}",
  missing: "Missing: {count}",
  definitions: "Definitions: {count}",
  target: "Target: {value}",
  importSuccessful: "Import Successful",
  importSuccessfulDescription:
    "{targetKey} was imported successfully. You can start a new import below or go to the Projects Overview.",
  goToProjectsOverview: "Go to Projects Overview",
  targetImported: "Target imported: {value}",
  targetPackage: "Target Package",
  targetSetDescription:
    "Target set. Download the package and upload it to start the import.",
  targetUploadOrEnter: "Upload the target package directly or enter id + version.",
  importStartedFor: "Import started for:",
  downloadPackages: "Download (packages2.fhir.org)",
  copyLink: "Copy Link",
  uploadTargetPackage: "Upload target package (.tgz)",
  uploadTargetHelper:
    "Download the target from packages2.fhir.org, then upload it here to start the import.",
  uploadTargetHint: "Drag & drop the target .tgz file here",
  uploadTargetOrExplorer: "Upload target package (.tgz) or FHIR Explorer project (.json/.zip)",
  uploadTargetOrExplorerHelper: "The package must contain package/package.json",
  uploadTargetOrExplorerHint: "Drag & drop .tgz, .json, or .zip files here",
  packageId: "Package ID",
  version: "Version",
  setTarget: "Set Target",
  dependencies: "Dependencies",
  dependenciesDescription:
    "Upload any missing dependency in any order. You can start multiple downloads at once.",
  uploadTargetToDetect: "Upload the target package to detect its dependencies.",
  allDependenciesResolved: "All dependencies resolved.",
  required: "Required: {value}",
  chooseVersion: "Choose version",
  setVersion: "Set Version",
  clear: "Clear",
  download: "Download:",
  selectVersionForLink: "Select a version to generate a link",
  openLink: "Open Link",
  uploadPackageOrExplorer: "Upload package (.tgz) or FHIR Explorer project (.json/.zip)",
  uploadPackageOrExplorerHelper:
    "Upload target or dependency packages. The importer will detect matches.",
  uploadPackageOrExplorerHint: "Drag & drop .tgz, .json, or .zip files here",
  importHistory: "Import History",
  importHistoryDescription: "Previously imported target packages.",
  noImportsYet: "No imports yet.",
  importLog: "Import Log",
  latestImportActions: "Latest actions during this import.",
  importLogHistory: "History of the last completed import.",
  showLog: "Show log ({count})",
  noLogEntries: "No log entries yet.",
  conflicts: "Conflicts",
  conflictsDescription: "Resolve these before the import is complete.",
  versionConflict: "Version conflict",
};

const LOCALE_TEXT = {
  de: {
    none: "Keine",
    failedFhirExplorerProjectImport: "Import der FHIR-Explorer-Projektdatei fehlgeschlagen.",
    fhirExplorerProjectImported:
      "FHIR-Explorer-Projekt importiert ({imported} Pakete, {skipped} übersprungen).",
    packageAlreadyImported: "Paket {packageKey} ist bereits importiert.",
    targetPackageImported: "Zielpaket {packageKey} importiert.",
    dependencyImported: "Abhängigkeit {packageKey} importiert.",
    packageImportedButNotMissing:
      "Paket {packageKey} importiert, war aber nicht als fehlend gelistet.",
    targetPackageAlreadyImported: "Zielpaket {packageKey} ist bereits importiert.",
    importingPackage: "Paket wird importiert",
    packageAlreadyImportedShort: "Paket {packageKey} bereits importiert.",
    importedPackageShort: "{packageKey} importiert.",
    errorPrefix: "Fehler: {error}",
    title: "Paket-Import",
    importer: "FHIR Importer",
    cancelImport: "Import abbrechen",
    projectsOverview: "Projektübersicht",
    home: "Startseite",
    intro:
      "Importiere FHIR-Pakete und alle transitiven Abhängigkeiten vollständig im Browser. Der Assistent aktualisiert sich nach jedem Upload.",
    imported: "Importiert: {count}",
    missing: "Fehlend: {count}",
    definitions: "Definitionen: {count}",
    target: "Ziel: {value}",
    importSuccessful: "Import erfolgreich",
    importSuccessfulDescription:
      "{targetKey} wurde erfolgreich importiert. Du kannst unten einen neuen Import starten oder zur Projektübersicht wechseln.",
    goToProjectsOverview: "Zur Projektübersicht",
    targetImported: "Ziel importiert: {value}",
    targetPackage: "Zielpaket",
    targetSetDescription:
      "Ziel ist gesetzt. Lade das Paket herunter und lade es hoch, um den Import zu starten.",
    targetUploadOrEnter: "Lade das Zielpaket direkt hoch oder gib ID + Version ein.",
    importStartedFor: "Import gestartet für:",
    downloadPackages: "Download (packages2.fhir.org)",
    copyLink: "Link kopieren",
    uploadTargetPackage: "Zielpaket hochladen (.tgz)",
    uploadTargetHelper:
      "Lade das Ziel von packages2.fhir.org herunter und lade es hier hoch, um den Import zu starten.",
    uploadTargetHint: "Ziehe die Ziel-.tgz-Datei hier hinein",
    uploadTargetOrExplorer: "Zielpaket (.tgz) oder FHIR-Explorer-Projekt (.json/.zip) hochladen",
    uploadTargetOrExplorerHelper: "Das Paket muss package/package.json enthalten",
    uploadTargetOrExplorerHint: "Ziehe .tgz-, .json- oder .zip-Dateien hier hinein",
    packageId: "Paket-ID",
    version: "Version",
    setTarget: "Ziel setzen",
    dependencies: "Abhängigkeiten",
    dependenciesDescription:
      "Lade fehlende Abhängigkeiten in beliebiger Reihenfolge hoch. Du kannst mehrere Downloads gleichzeitig starten.",
    uploadTargetToDetect:
      "Lade das Zielpaket hoch, um dessen Abhängigkeiten zu erkennen.",
    allDependenciesResolved: "Alle Abhängigkeiten sind aufgelöst.",
    required: "Erforderlich: {value}",
    chooseVersion: "Version wählen",
    setVersion: "Version setzen",
    clear: "Leeren",
    download: "Download:",
    selectVersionForLink: "Wähle eine Version, um einen Link zu erzeugen",
    openLink: "Link öffnen",
    uploadPackageOrExplorer: "Paket (.tgz) oder FHIR-Explorer-Projekt (.json/.zip) hochladen",
    uploadPackageOrExplorerHelper:
      "Lade Ziel- oder Abhängigkeitspakete hoch. Der Importer erkennt passende Pakete automatisch.",
    uploadPackageOrExplorerHint: "Ziehe .tgz-, .json- oder .zip-Dateien hier hinein",
    importHistory: "Import-Historie",
    importHistoryDescription: "Bisher importierte Zielpakete.",
    noImportsYet: "Noch keine Importe.",
    importLog: "Import-Log",
    latestImportActions: "Neueste Aktionen während dieses Imports.",
    importLogHistory: "Verlauf des letzten abgeschlossenen Imports.",
    showLog: "Log anzeigen ({count})",
    noLogEntries: "Noch keine Log-Einträge.",
    conflicts: "Konflikte",
    conflictsDescription: "Löse diese Konflikte, bevor der Import abgeschlossen ist.",
    versionConflict: "Versionskonflikt",
  },
  en: EN_TEXT,
  fr: {
    ...EN_TEXT,
    none: "Aucun",
    failedFhirExplorerProjectImport: "Echec de l'import du fichier projet FHIR Explorer.",
    fhirExplorerProjectImported:
      "Projet compose importe ({imported} paquets, {skipped} ignores).",
    packageAlreadyImported: "Le paquet {packageKey} est deja importe.",
    targetPackageImported: "Paquet cible {packageKey} importe.",
    dependencyImported: "Dependance {packageKey} importee.",
    packageImportedButNotMissing:
      "Paquet {packageKey} importe, mais il n'etait pas marque manquant.",
    targetPackageAlreadyImported: "Le paquet cible {packageKey} est deja importe.",
    importingPackage: "Import du paquet",
    packageAlreadyImportedShort: "Paquet {packageKey} deja importe.",
    importedPackageShort: "{packageKey} importe.",
    errorPrefix: "Erreur: {error}",
    title: "Import de paquet",
    importer: "Importeur FHIR",
    cancelImport: "Annuler l'import",
    projectsOverview: "Vue d'ensemble des projets",
    home: "Accueil",
    intro:
      "Importez des paquets FHIR et toutes les dependances transitives dans le navigateur. L'assistant se met a jour apres chaque televersement.",
    imported: "Importes: {count}",
    missing: "Manquants: {count}",
    definitions: "Definitions: {count}",
    target: "Cible: {value}",
    importSuccessful: "Import reussi",
    importSuccessfulDescription:
      "{targetKey} a ete importe avec succes. Vous pouvez lancer un nouvel import ou revenir a la vue des projets.",
    goToProjectsOverview: "Aller a la vue des projets",
    targetImported: "Cible importee: {value}",
    targetPackage: "Paquet cible",
    targetSetDescription:
      "Cible definie. Telechargez le paquet puis televersez-le pour lancer l'import.",
    targetUploadOrEnter: "Televersez directement le paquet cible ou saisissez id + version.",
    importStartedFor: "Import demarre pour:",
    downloadPackages: "Telecharger (packages2.fhir.org)",
    uploadTargetPackage: "Televerser le paquet cible (.tgz)",
    uploadTargetHelper:
      "Telechargez la cible depuis packages2.fhir.org, puis televersez-la ici pour demarrer l'import.",
    uploadTargetHint: "Glisser-deposer le fichier .tgz cible ici",
    uploadTargetOrExplorer: "Televerser le paquet cible (.tgz) ou un projet FHIR Explorer (.json/.zip)",
    uploadTargetOrExplorerHelper: "Le paquet doit contenir package/package.json",
    uploadTargetOrExplorerHint: "Glisser-deposer des fichiers .tgz, .json ou .zip ici",
    packageId: "ID du paquet",
    version: "Version",
    setTarget: "Definir la cible",
    dependencies: "Dependances",
    dependenciesDescription:
      "Televersez les dependances manquantes dans n'importe quel ordre. Vous pouvez lancer plusieurs telechargements en parallele.",
    uploadTargetToDetect: "Televersez le paquet cible pour detecter ses dependances.",
    allDependenciesResolved: "Toutes les dependances sont resolues.",
    required: "Requis: {value}",
    chooseVersion: "Choisir la version",
    setVersion: "Definir la version",
    clear: "Effacer",
    download: "Telecharger:",
    selectVersionForLink: "Selectionnez une version pour generer un lien",
    openLink: "Ouvrir le lien",
    uploadPackageOrExplorer: "Televerser un paquet (.tgz) ou un projet FHIR Explorer (.json/.zip)",
    uploadPackageOrExplorerHelper:
      "Televersez des paquets cibles ou de dependance. L'importeur detectera les correspondances.",
    uploadPackageOrExplorerHint: "Glisser-deposer des fichiers .tgz, .json ou .zip ici",
    importHistory: "Historique d'import",
    importHistoryDescription: "Paquets cibles importes precedemment.",
    noImportsYet: "Aucun import pour le moment.",
    importLog: "Journal d'import",
    latestImportActions: "Dernieres actions pendant cet import.",
    importLogHistory: "Historique du dernier import termine.",
    showLog: "Afficher le journal ({count})",
    noLogEntries: "Aucune entree de journal.",
    conflicts: "Conflits",
    conflictsDescription: "Resolvez ces conflits avant la fin de l'import.",
    versionConflict: "Conflit de version",
    copyLink: "Copier le lien",
  },
  es: {
    ...EN_TEXT,
    none: "Ninguno",
    failedFhirExplorerProjectImport: "Error al importar el archivo de proyecto FHIR Explorer.",
    fhirExplorerProjectImported:
      "Proyecto compose importado ({imported} paquetes, {skipped} omitidos).",
    packageAlreadyImported: "El paquete {packageKey} ya esta importado.",
    targetPackageImported: "Paquete objetivo {packageKey} importado.",
    dependencyImported: "Dependencia {packageKey} importada.",
    packageImportedButNotMissing:
      "Paquete {packageKey} importado, pero no estaba marcado como faltante.",
    targetPackageAlreadyImported: "El paquete objetivo {packageKey} ya esta importado.",
    importingPackage: "Importando paquete",
    packageAlreadyImportedShort: "Paquete {packageKey} ya importado.",
    importedPackageShort: "{packageKey} importado.",
    errorPrefix: "Error: {error}",
    title: "Importacion de paquetes",
    importer: "Importador FHIR",
    cancelImport: "Cancelar importacion",
    projectsOverview: "Resumen de proyectos",
    home: "Inicio",
    intro:
      "Importa paquetes FHIR y todas las dependencias transitivas en el navegador. El asistente se actualiza tras cada carga.",
    imported: "Importados: {count}",
    missing: "Faltantes: {count}",
    definitions: "Definiciones: {count}",
    target: "Objetivo: {value}",
    importSuccessful: "Importacion correcta",
    importSuccessfulDescription:
      "{targetKey} se importo correctamente. Puedes iniciar una nueva importacion o volver al resumen de proyectos.",
    goToProjectsOverview: "Ir al resumen de proyectos",
    targetImported: "Objetivo importado: {value}",
    targetPackage: "Paquete objetivo",
    targetSetDescription:
      "Objetivo definido. Descarga el paquete y subelo para iniciar la importacion.",
    targetUploadOrEnter: "Sube el paquete objetivo directamente o introduce id + version.",
    importStartedFor: "Importacion iniciada para:",
    downloadPackages: "Descargar (packages2.fhir.org)",
    uploadTargetPackage: "Subir paquete objetivo (.tgz)",
    uploadTargetHelper:
      "Descarga el objetivo desde packages2.fhir.org y subelo aqui para iniciar la importacion.",
    uploadTargetHint: "Arrastra y suelta el archivo .tgz objetivo aqui",
    uploadTargetOrExplorer: "Subir paquete objetivo (.tgz) o proyecto FHIR Explorer (.json/.zip)",
    uploadTargetOrExplorerHelper: "El paquete debe contener package/package.json",
    uploadTargetOrExplorerHint: "Arrastra y suelta archivos .tgz, .json o .zip aqui",
    packageId: "ID del paquete",
    version: "Version",
    setTarget: "Definir objetivo",
    dependencies: "Dependencias",
    dependenciesDescription:
      "Sube cualquier dependencia faltante en cualquier orden. Puedes iniciar varias descargas a la vez.",
    uploadTargetToDetect: "Sube el paquete objetivo para detectar sus dependencias.",
    allDependenciesResolved: "Todas las dependencias resueltas.",
    required: "Requerido: {value}",
    chooseVersion: "Elegir version",
    setVersion: "Definir version",
    clear: "Limpiar",
    download: "Descargar:",
    selectVersionForLink: "Selecciona una version para generar un enlace",
    openLink: "Abrir enlace",
    uploadPackageOrExplorer: "Subir paquete (.tgz) o proyecto FHIR Explorer (.json/.zip)",
    uploadPackageOrExplorerHelper:
      "Sube paquetes objetivo o de dependencia. El importador detectara coincidencias.",
    uploadPackageOrExplorerHint: "Arrastra y suelta archivos .tgz, .json o .zip aqui",
    importHistory: "Historial de importacion",
    importHistoryDescription: "Paquetes objetivo importados anteriormente.",
    noImportsYet: "Aun no hay importaciones.",
    importLog: "Registro de importacion",
    latestImportActions: "Ultimas acciones durante esta importacion.",
    importLogHistory: "Historial de la ultima importacion completada.",
    showLog: "Mostrar registro ({count})",
    noLogEntries: "No hay entradas en el registro.",
    conflicts: "Conflictos",
    conflictsDescription: "Resuelve estos conflictos antes de completar la importacion.",
    versionConflict: "Conflicto de version",
    copyLink: "Copiar enlace",
  },
  it: {
    ...EN_TEXT,
    none: "Nessuno",
    failedFhirExplorerProjectImport: "Importazione del file progetto FHIR Explorer non riuscita.",
    fhirExplorerProjectImported:
      "Progetto compose importato ({imported} pacchetti, {skipped} saltati).",
    packageAlreadyImported: "Il pacchetto {packageKey} e gia importato.",
    targetPackageImported: "Pacchetto target {packageKey} importato.",
    dependencyImported: "Dipendenza {packageKey} importata.",
    packageImportedButNotMissing:
      "Pacchetto {packageKey} importato, ma non era segnato come mancante.",
    targetPackageAlreadyImported: "Il pacchetto target {packageKey} e gia importato.",
    importingPackage: "Importazione pacchetto",
    packageAlreadyImportedShort: "Pacchetto {packageKey} gia importato.",
    importedPackageShort: "{packageKey} importato.",
    errorPrefix: "Errore: {error}",
    title: "Importazione pacchetti",
    importer: "Importatore FHIR",
    cancelImport: "Annulla importazione",
    projectsOverview: "Panoramica progetti",
    home: "Home",
    intro:
      "Importa pacchetti FHIR e tutte le dipendenze transitive nel browser. La procedura guidata si aggiorna dopo ogni caricamento.",
    imported: "Importati: {count}",
    missing: "Mancanti: {count}",
    definitions: "Definizioni: {count}",
    target: "Target: {value}",
    importSuccessful: "Importazione riuscita",
    importSuccessfulDescription:
      "{targetKey} e stato importato con successo. Puoi avviare una nuova importazione o tornare alla panoramica progetti.",
    goToProjectsOverview: "Vai alla panoramica progetti",
    targetImported: "Target importato: {value}",
    targetPackage: "Pacchetto target",
    targetSetDescription:
      "Target impostato. Scarica il pacchetto e caricalo per avviare l'importazione.",
    targetUploadOrEnter: "Carica direttamente il pacchetto target o inserisci id + versione.",
    importStartedFor: "Importazione avviata per:",
    downloadPackages: "Scarica (packages2.fhir.org)",
    uploadTargetPackage: "Carica pacchetto target (.tgz)",
    uploadTargetHelper:
      "Scarica il target da packages2.fhir.org, poi caricalo qui per avviare l'importazione.",
    uploadTargetHint: "Trascina qui il file .tgz target",
    uploadTargetOrExplorer: "Carica pacchetto target (.tgz) o progetto FHIR Explorer (.json/.zip)",
    uploadTargetOrExplorerHelper: "Il pacchetto deve contenere package/package.json",
    uploadTargetOrExplorerHint: "Trascina qui file .tgz, .json o .zip",
    packageId: "ID pacchetto",
    version: "Versione",
    setTarget: "Imposta target",
    dependencies: "Dipendenze",
    dependenciesDescription:
      "Carica qualsiasi dipendenza mancante in qualsiasi ordine. Puoi avviare piu download contemporaneamente.",
    uploadTargetToDetect: "Carica il pacchetto target per rilevare le sue dipendenze.",
    allDependenciesResolved: "Tutte le dipendenze risolte.",
    required: "Richiesto: {value}",
    chooseVersion: "Scegli versione",
    setVersion: "Imposta versione",
    clear: "Pulisci",
    download: "Scarica:",
    selectVersionForLink: "Seleziona una versione per generare un link",
    openLink: "Apri link",
    uploadPackageOrExplorer: "Carica pacchetto (.tgz) o progetto FHIR Explorer (.json/.zip)",
    uploadPackageOrExplorerHelper:
      "Carica pacchetti target o di dipendenza. L'importatore rilevera le corrispondenze.",
    uploadPackageOrExplorerHint: "Trascina qui file .tgz, .json o .zip",
    importHistory: "Cronologia importazioni",
    importHistoryDescription: "Pacchetti target importati in precedenza.",
    noImportsYet: "Nessuna importazione.",
    importLog: "Log importazione",
    latestImportActions: "Ultime azioni durante questa importazione.",
    importLogHistory: "Cronologia dell'ultima importazione completata.",
    showLog: "Mostra log ({count})",
    noLogEntries: "Nessuna voce di log.",
    conflicts: "Conflitti",
    conflictsDescription: "Risolvi questi conflitti prima del completamento dell'importazione.",
    versionConflict: "Conflitto di versione",
    copyLink: "Copia link",
  },
};

export const useImportWizardText = () => {
  const { locale } = useI18n();
  const text = byLocale(locale, LOCALE_TEXT);

  const format = useCallback(
    (template: string, values: Record<string, string | number>) =>
      template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? "")),
    []
  );

  return { locale, text, format };
};

