import { useI18n } from "@/components/i18n/I18nProvider";
import { byLocale } from "@/lib/i18n/select";

export const useResourceDetailText = () => {
  const { locale } = useI18n();
  const enText = {
    unknownLabel: "Unknown",
    fieldsTitle: "Fields",
    pickResourceToEdit: "Pick a resource to edit",
    selectResourceToStart: "Select a resource to start editing its fields.",
    requiredCount: "{required} required, {optional} optional",
    ariaToggleSearch: "Toggle search",
    remove: "Remove",
    addField: "Add field",
    searchFields: "Search fields",
    noFieldsForProfile: "No fields available for this profile.",
    unknownFieldsTitle: "Unknown fields",
    unknownField: "Unknown field",
    notInProfile: "Not in profile",
    addValue: "Add value",
    addFieldDialogTitle: "Add field",
    addFieldDialogDescription: "Search and select a field to add to this resource.",
    noFieldsAvailable: "No fields available.",
    close: "Close",
    required: "Required",
    multiple: "Multiple",
    brokenReferenceTarget: "Broken reference target",
    missingTarget: "Missing target",
    validationErrorTooltip: "{count} validation error{suffix}",
    noValuesYet: "No values yet.",
    groupEntries: "Group · {count} entries",
    addEntry: "Add entry",
    noEntriesYet: "No entries yet.",
    entry: "Entry {index}",
    object: "Object",
    noFieldsYet: "No fields yet.",
    rawJson: "Raw JSON",
    jsonMustBeObject: "JSON must be an object.",
    invalidJson: "Invalid JSON",
    popupSearchPlaceholder: "Search",
    popupNoOptions: "No options available.",
    popupClear: "Clear",
    setDisplay: "Set display",
    selectReference: "Select reference",
    searchResources: "Search resources",
    noMatchingResources: "No matching resources.",
    referencePlaceholder: "ResourceType/id",
    openReferencedResource: "Open referenced resource",
    selectSystem: "Select system",
    searchSystems: "Search systems",
    selectIdentifierType: "Select identifier type",
    searchIdentifierTypes: "Search identifier types",
    systemUri: "System URI",
    identifierValue: "Identifier value",
    useOptional: "Use (optional)",
    searchUseValues: "Search use values",
    typeTextOptional: "Type text (optional)",
    typeSystemOptional: "Type system (optional)",
    typeCodeOptional: "Type code (optional)",
    typeDisplayOptional: "Type display (optional)",
    enabled: "Enabled",
    selectValue: "Select value",
    searchValues: "Search values",
    enterCode: "Enter code",
    orEnterCustomValue: "Or enter a custom value",
    systemUrl: "System URL",
    code: "Code",
    displayOptional: "Display (optional)",
    textOptional: "Text (optional)",
    searchValue: "Search value",
    removeValue: "Remove value",
    enterValue: "Enter value",
    selectType: "Select type",
    typeLabel: "Type",
    moveUp: "Move up",
    moveDown: "Move down",
    duplicate: "Duplicate",
    mustSupport: "Must Support",
    modifierBadge: "Modifier",
    fixedBadge: "Fixed",
    bindingLabel: "Binding",
    extensionUrl: "Extension URL",
    unknownExtensionValue: "Value",
    otherEntries: "Other entries",
    addSubField: "Add sub-field",
    collapse: "Collapse",
    expand: "Expand",
    narrativeStatus: "Status",
    narrativeDiv: "Content (XHTML)",
    noEditableChildren: "No structured definition available — editing as JSON.",
    itemLabel: "Item {index}",
    metadataSection: "Metadata",
    createReferenceTarget: "Create target resource",
    searchTargetTypes: "Search target types",
    quantityValue: "Value",
    quantityUnit: "Unit",
    selectUnit: "Select unit",
    searchUnits: "Search units",
    customUnitPlaceholder: "Unit text (free form)",
    contactPointSystem: "System",
    contactPointValue: "Value",
    primitiveExtensions: "Extensions ({count})",
  };

  const text = byLocale(locale, {
    de: {
      unknownLabel: "Unbekannt",
      fieldsTitle: "Felder",
      pickResourceToEdit: "Wähle eine Ressource zum Bearbeiten",
      selectResourceToStart: "Wähle eine Ressource aus, um ihre Felder zu bearbeiten.",
      requiredCount: "{required} erforderlich, {optional} optional",
      ariaToggleSearch: "Suche umschalten",
      remove: "Entfernen",
      addField: "Feld hinzufügen",
      searchFields: "Felder suchen",
      noFieldsForProfile: "Keine Felder für dieses Profil verfügbar.",
      unknownFieldsTitle: "Unbekannte Felder",
      unknownField: "Unbekanntes Feld",
      notInProfile: "Nicht im Profil",
      addValue: "Wert hinzufügen",
      addFieldDialogTitle: "Feld hinzufügen",
      addFieldDialogDescription: "Suche ein Feld und füge es dieser Ressource hinzu.",
      noFieldsAvailable: "Keine Felder verfügbar.",
      close: "Schließen",
      required: "Erforderlich",
      multiple: "Mehrfach",
      brokenReferenceTarget: "Fehlendes Referenzziel",
      missingTarget: "Fehlendes Ziel",
      validationErrorTooltip: "{count} Validierungsfehler",
      noValuesYet: "Noch keine Werte.",
      groupEntries: "Gruppe · {count} Einträge",
      addEntry: "Eintrag hinzufügen",
      noEntriesYet: "Noch keine Einträge.",
      entry: "Eintrag {index}",
      object: "Objekt",
      noFieldsYet: "Noch keine Felder.",
      rawJson: "Rohes JSON",
      jsonMustBeObject: "JSON muss ein Objekt sein.",
      invalidJson: "Ungültiges JSON",
      popupSearchPlaceholder: "Suchen",
      popupNoOptions: "Keine Optionen verfügbar.",
      popupClear: "Leeren",
      setDisplay: "Display setzen",
      selectReference: "Referenz auswählen",
      searchResources: "Ressourcen suchen",
      noMatchingResources: "Keine passenden Ressourcen.",
      referencePlaceholder: "Ressourcentyp/ID",
      openReferencedResource: "Referenzierte Ressource öffnen",
      selectSystem: "System auswählen",
      searchSystems: "Systeme suchen",
      selectIdentifierType: "Identifier-Typ auswählen",
      searchIdentifierTypes: "Identifier-Typen suchen",
      systemUri: "System-URI",
      identifierValue: "Identifier-Wert",
      useOptional: "Use (optional)",
      searchUseValues: "Use-Werte suchen",
      typeTextOptional: "Text (optional)",
      typeSystemOptional: "Type-System (optional)",
      typeCodeOptional: "Type-Code (optional)",
      typeDisplayOptional: "Type-Display (optional)",
      enabled: "Aktiv",
      selectValue: "Wert auswählen",
      searchValues: "Werte suchen",
      enterCode: "Code eingeben",
      orEnterCustomValue: "Oder einen eigenen Wert eingeben",
      systemUrl: "System-URL",
      code: "Code",
      displayOptional: "Display (optional)",
      textOptional: "Text (optional)",
      searchValue: "Wert suchen",
      removeValue: "Wert entfernen",
      enterValue: "Wert eingeben",
      selectType: "Typ auswählen",
      typeLabel: "Typ",
      moveUp: "Nach oben",
      moveDown: "Nach unten",
      duplicate: "Duplizieren",
      mustSupport: "Must Support",
      modifierBadge: "Modifier",
      fixedBadge: "Fixiert",
      bindingLabel: "Binding",
      extensionUrl: "Extension-URL",
      unknownExtensionValue: "Wert",
      otherEntries: "Weitere Einträge",
      addSubField: "Unterfeld hinzufügen",
      collapse: "Einklappen",
      expand: "Ausklappen",
      narrativeStatus: "Status",
      narrativeDiv: "Inhalt (XHTML)",
      noEditableChildren: "Keine strukturierte Definition verfügbar — Bearbeitung als JSON.",
      itemLabel: "Eintrag {index}",
      metadataSection: "Metadaten",
      createReferenceTarget: "Zielressource anlegen",
      searchTargetTypes: "Zieltypen suchen",
      quantityValue: "Wert",
      quantityUnit: "Einheit",
      selectUnit: "Einheit auswählen",
      searchUnits: "Einheiten suchen",
      customUnitPlaceholder: "Einheitentext (Freitext)",
      contactPointSystem: "System",
      contactPointValue: "Wert",
      primitiveExtensions: "Extensions ({count})",
    },
    en: enText,
    fr: {
      ...enText,
      fieldsTitle: "Champs",
      remove: "Supprimer",
      addField: "Ajouter un champ",
      addFieldDialogTitle: "Ajouter un champ",
      addValue: "Ajouter une valeur",
      close: "Fermer",
      searchFields: "Rechercher des champs",
      removeValue: "Supprimer la valeur",
      enterValue: "Saisir une valeur",
    },
    es: {
      ...enText,
      fieldsTitle: "Campos",
      remove: "Eliminar",
      addField: "Agregar campo",
      addFieldDialogTitle: "Agregar campo",
      addValue: "Agregar valor",
      close: "Cerrar",
      searchFields: "Buscar campos",
      removeValue: "Eliminar valor",
      enterValue: "Introducir valor",
    },
    it: {
      ...enText,
      fieldsTitle: "Campi",
      remove: "Rimuovi",
      addField: "Aggiungi campo",
      addFieldDialogTitle: "Aggiungi campo",
      addValue: "Aggiungi valore",
      close: "Chiudi",
      searchFields: "Cerca campi",
      removeValue: "Rimuovi valore",
      enterValue: "Inserisci valore",
    },
  });

  return { locale, text };
};

